- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile.sh"
  when: ansible_env.SHELL == "/bin/zsh"
