- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install system packages
  homebrew:
    name: ["coreutils", "fasd", "git", "jq", "tree", "wget", "zsh-completions"]
    state: latest

# https://github.com/robbyrussell/oh-my-zsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/"

# https://www.iterm2.com/documentation-shell-integration.html
- name: Download iTerm2 Shell Integration
  shell: sh -c "curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh"

# https://github.com/zsh-users/zsh-syntax-highlighting
- name: Checkout zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting"
    update: yes

# https://github.com/seebi/dircolors-solarized
- name: Checkout dircolors-solarized
  git:
    repo: https://github.com/seebi/dircolors-solarized
    dest: "{{ ansible_env.HOME }}/.dircolors-solarized"
    update: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Downloads"
    - "{{ ansible_env.HOME }}/Projects"

- name: Link hal-9000
  file:
    src: "{{ REPO_ROOT }}"
    dest: "{{ ansible_env.HOME }}/Projects/hal-9000"
    state: link

- name: Run hal sync
  command: "{{ REPO_ROOT }}/bin/hal sync"

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile.sh"
  when: ansible_env.SHELL == "/bin/zsh"
