- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Install system packages
  homebrew:
    name: ["git", "jq", "tree", "wget"]
    state: latest

# https://github.com/ohmyzsh/ohmyzsh
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Downloads"
    - "{{ ansible_env.HOME }}/Projects"

- name: Link hal-9000
  file:
    src: "{{ REPO_ROOT }}"
    dest: "{{ ansible_env.HOME }}/Projects/hal-9000"
    state: link

- name: Run hal sync
  command: "{{ REPO_ROOT }}/bin/hal sync"

- name: Enable hal environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source {{ REPO_ROOT }}/playbooks/roles/basic/files/hal_profile.sh"
  when: ansible_env.SHELL == "/bin/zsh"
