# https://github.com/yyuu/pyenv
- name: Install pyenv
  homebrew:
    name: ["openssl", "readline", "sqlite3", "xz", "zlib", "pyenv"]
    state: latest

- name: Enable pyenv environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/python/files/py_profile.sh
  when: ansible_env.SHELL == "/bin/zsh"
