# https://github.com/yyuu/pyenv
- name: Install pyenv
  homebrew:
    name: ["openssl", "readline", "zlib", "pyenv"]
    state: present

- name: Install Python {{ PYTHON_2_VERSION }} via pyenv
  command: "pyenv install {{ PYTHON_2_VERSION }}"
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_2_VERSION }}"

- name: Install Python {{ PYTHON_3_VERSION }} via pyenv
  shell: |
    export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
    export CPPFLAGS="-I/usr/local/opt/zlib/include"
    export LDFLAGS="-L/usr/local/opt/zlib/lib"
    pyenv install {{ PYTHON_3_VERSION }}
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_3_VERSION }}"

- name: Install Python 3 tools
  pip:
    executable: "{{ ansible_env.HOME }}/.pyenv/versions/{{ PYTHON_3_VERSION }}/bin/pip3"
    requirements: "{{ REPO_ROOT }}/playbooks/roles/python/files/requirements.txt"

- name: Specify the default Python version
  command: "pyenv global {{ PYTHON_3_VERSION }} {{ PYTHON_2_VERSION }}"

- name: Enable pyenv environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/python/files/pyenv_profile
  when: ansible_env.SHELL == "/bin/zsh"
