- name: Install prerequisite packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - gnu-tar

- name: Install Java 8
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask-versions/java8

- name: Install Scala 2.11
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - scala@2.11

- name: Create /usr/local/share/apache-spark
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/apache-spark

# https://spark.apache.org/downloads.html
- name: Unarchive Spark
  unarchive:
    src: http://apache.stu.edu.tw/spark/spark-{{ SPARK_VERSION }}/spark-{{ SPARK_VERSION }}-bin-hadoop2.7.tgz
    remote_src: yes
    dest: /usr/local/share/apache-spark
    creates: /usr/local/share/apache-spark/spark-{{ SPARK_VERSION }}

- name: Rename Spark directory
  command: mv spark-{{ SPARK_VERSION }}-bin-hadoop2.7 spark-{{ SPARK_VERSION }}
  args:
    chdir: /usr/local/share/apache-spark
    creates: spark-{{ SPARK_VERSION }}
    removes: spark-{{ SPARK_VERSION }}-bin-hadoop2.7

- name: Enable Spark environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/spark/files/spark_profile
  when: ansible_env.SHELL == "/bin/zsh"
