- name: Install Go
  homebrew:
    name: ["go"]
    state: latest

- name: Enable Go environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/go/files/go_profile.sh
  when: ansible_env.SHELL == "/bin/zsh"
