- name: Create ~/vendors
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/vendors"

# https://cloud.google.com/sdk/docs/quickstart-macos
- name: Unarchive Google Cloud SDK
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-321.0.0-darwin-x86_64.tar.gz
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/vendors"
    creates: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk"

- name: Install gcloud components
  command: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components install gsutil cloud_sql_proxy"
  register: command_result
  changed_when: "'All components are up to date' not in command_result.stderr"

- name: Update gcloud components
  shell: /usr/local/opt/coreutils/libexec/gnubin/yes 'y' | {{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components update
