- name: Install Node.js
  homebrew:
    name: ["node@10"]
    state: latest

- name: Enable Node.js environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - "source {{ REPO_ROOT }}/playbooks/roles/node/files/node_profile"
  when: ansible_env.SHELL == "/bin/zsh"

- name: Install Node.js packages
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
    executable: /usr/local/opt/node@10/bin/npm
  with_items:
    - bunyan
    - pangu
    - yarn
