- name: Install Node.js
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - node@10

- name: Install Node.js tools
  npm:
    name: "{{ item }}"
    state: present
  with_items:
    - yarn

- name: Enable Node.js environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/node/files/node_profile
  when: ansible_env.SHELL == "/bin/zsh"
