- name: Install prerequisite packages
  homebrew:
    name: ["coreutils", "fzf", "gnu-tar", "jq"]
    state: latest

- name: Install kubectl
  homebrew:
    name: ["kubernetes-cli"]
    state: latest

# https://github.com/derailed/k9s
- name: Install k9s
  homebrew:
    name: ["derailed/k9s/k9s"]
    state: latest

# https://github.com/kubermatic/fubectl
- name: Install fubectl
  shell: sh -c "curl -L https://rawgit.com/kubermatic/fubectl/master/fubectl.source -o ~/.fubectl.source"

# https://github.com/superbrothers/zsh-kubectl-prompt
- name: Install zsh-kubectl-prompt
  git:
    repo: https://github.com/superbrothers/zsh-kubectl-prompt.git
    dest: "{{ ansible_env.HOME }}/.zsh-kubectl-prompt"
    update: yes

- name: Enable Kubernetes environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile.sh
  when: ansible_env.SHELL == "/bin/zsh"
