- name: Install prerequisite packages
  homebrew:
    name: ["coreutils", "fzf", "gnu-tar", "jq"]
    state: latest

- name: Create ~/vendors
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/vendors"

# https://cloud.google.com/sdk/docs/quickstart-macos
- name: Unarchive Google Cloud SDK
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-297.0.1-darwin-x86_64.tar.gz
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/vendors"
    creates: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk"

- name: Install gcloud components
  command: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components install gsutil cloud_sql_proxy"
  register: command_result
  changed_when: "'All components are up to date' not in command_result.stderr"

- name: Update gcloud components
  shell: /usr/local/opt/coreutils/libexec/gnubin/yes 'y' | {{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components update

# https://github.com/superbrothers/zsh-kubectl-prompt
- name: Checkout zsh-kubectl-prompt
  git:
    repo: https://github.com/superbrothers/zsh-kubectl-prompt.git
    dest: "{{ ansible_env.HOME }}/vendors/zsh-kubectl-prompt"
    update: yes

# https://github.com/derailed/k9s
# https://github.com/derailed/popeye
# https://github.com/wercker/stern
- name: Install Kubernetes tools
  homebrew:
    name: ["kubernetes-cli", "derailed/k9s/k9s", "derailed/popeye/popeye", "stern"]
    state: latest

# https://github.com/kubermatic/fubectl
- name: Install fubectl
  shell: sh -c "curl -L https://rawgit.com/kubermatic/fubectl/master/fubectl.source -o ~/.fubectl.source"

- name: Enable Kubernetes environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile.sh
  when: ansible_env.SHELL == "/bin/zsh"
