- name: Install prerequisite packages
  homebrew:
    name: ["coreutils", "fzf", "gnu-tar", "jq"]
    state: latest

- name: Create ~/vendors
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/vendors"

# https://cloud.google.com/sdk/docs/quickstart-macos
- name: Unarchive Google Cloud SDK
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-234.0.0-darwin-x86_64.tar.gz
    remote_src: yes
    dest: "{{ ansible_env.HOME }}/vendors"
    creates: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk"

- name: Install gcloud components
  command: "{{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components install gsutil"
  register: command_result
  changed_when: " 'All components are up to date' not in command_result.stderr"

- name: Update gcloud components
  shell: /usr/local/opt/coreutils/libexec/gnubin/yes 'y' | {{ ansible_env.HOME }}/vendors/google-cloud-sdk/bin/gcloud components update

# https://github.com/derailed/k9s
- name: Homebrew tap derailed/k9s
  homebrew_tap:
    name: derailed/k9s

# https://github.com/superbrothers/zsh-kubectl-prompt
- name: Homebrew tap superbrothers/zsh-kubectl-prompt
  homebrew_tap:
    name: superbrothers/zsh-kubectl-prompt
    url: git://github.com/superbrothers/zsh-kubectl-prompt.git

# https://github.com/wercker/stern
- name: Install Kubernetes tools
  homebrew:
    name: ["kubernetes-cli", "k9s", "stern", "zsh-kubectl-prompt"]
    state: latest

# https://github.com/kubermatic/fubectl
- name: Install fubectl
  shell: sh -c "curl -L https://rawgit.com/kubermatic/fubectl/master/fubectl.source -o ~/.fubectl.source"

- name: Enable Kubernetes environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile
  when: ansible_env.SHELL == "/bin/zsh"
