- name: Install prerequisite packages
  homebrew:
    name: ["coreutils", "fzf", "gnu-tar", "jq"]
    state: latest

# https://github.com/superbrothers/zsh-kubectl-prompt
- name: Checkout zsh-kubectl-prompt
  git:
    repo: https://github.com/superbrothers/zsh-kubectl-prompt.git
    dest: "{{ ansible_env.HOME }}/vendors/zsh-kubectl-prompt"
    update: yes

# https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html
- name: Homebrew tap weaveworks/tap
  community.general.homebrew_tap:
    name: weaveworks/tap
    state: present

# https://github.com/derailed/k9s
# https://github.com/derailed/popeye
# https://github.com/pulumi/kubespy
# https://github.com/wercker/stern
- name: Install Kubernetes tools
  homebrew:
    name: ["kubernetes-cli", "derailed/k9s/k9s", "derailed/popeye/popeye", "kubespy", "stern", "weaveworks/tap/eksctl"]
    state: latest

# https://github.com/kubermatic/fubectl
- name: Install fubectl
  shell: sh -c "curl -L https://rawgit.com/kubermatic/fubectl/master/fubectl.source -o ~/.fubectl.source"

- name: Enable Kubernetes environment in .zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile.sh
  when: ansible_env.SHELL == "/bin/zsh"
